// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_appsync_graphqlEndpoint": "https://ofhprva56betdjzolvamf7o3ra.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gvodikp5uragdkdb2vpvbqi22q"
};


export default awsconfig;
